import { analyze7Days } from './analysis.js'
import { useState } from 'react'
import { useLoad, Status } from './useLoad.jsx'
import { requestAiAnalysis } from './aiAnalysis.js'

const Mix = ({ m }) => (
  <div className="mix">
    <span>😊 Good {m.good}</span><span>😐 Normal {m.normal}</span><span>😞 Bad {m.bad}</span>
  </div>
)

const trendLabels = [['sleep', '🌙 Sleep'], ['water', '💧 Water'], ['exercise', '🏃 Exercise'], ['mood', '😊 Mood'], ['food', '🥗 Food']]

function AiPanel() {
  const [state, setState] = useState({ phase: 'idle', result: null, error: '' })

  async function run() {
    setState({ phase: 'loading', result: null, error: '' })
    try {
      setState({ phase: 'done', result: await requestAiAnalysis(), error: '' })
    } catch (e) {
      setState({ phase: 'error', result: null, error: e.message })
    }
  }

  const r = state.result
  const ai = r && r.status === 'ok' ? r.analysis : null
  return (
    <>
      <div className="card">
        <h3>🤖 AI Analysis</h3>
        <p className="muted">AI reads your last 7 days from the database and writes a short wellness summary. It is general coaching, not medical advice.</p>
        <button className="primary" onClick={run} disabled={state.phase === 'loading'}>
          {state.phase === 'loading' ? 'Analyzing…' : ai ? 'Analyze again' : 'Analyze with AI'}
        </button>
        {state.phase === 'error' && <p className="error" role="alert">Could not get the analysis: {state.error}</p>}
        {r && r.status === 'insufficient' && <p className="muted" style={{ marginTop: 12 }}>{r.message}</p>}
      </div>

      {ai && (
        <>
          <div className="card">
            <h3>📋 Summary</h3>
            <p>{ai.summary}</p>
            <div className="trends">
              {trendLabels.map(([k, label]) => ai.trends[k] && <div className="row" key={k}><b>{label}</b><span>{ai.trends[k]}</span></div>)}
            </div>
            {ai.data_note && <p className="muted small">ℹ️ {ai.data_note}</p>}
          </div>
          <div className="grid2">
            <div className="card"><h3>✅ Strengths</h3><ul>{ai.strengths.map((t) => <li key={t}>{t}</li>)}</ul></div>
            <div className="card"><h3>🌱 Improvements</h3><ul>{ai.improvements.map((t) => <li key={t}>{t}</li>)}</ul></div>
          </div>
          <div className="card">
            <h3>💡 Recommendations</h3>
            <ol>{ai.recommendations.map((t) => <li key={t}>{t}</li>)}</ol>
            <p className="muted small">Generated by AI from your self-reported data. Not a medical diagnosis.</p>
          </div>
        </>
      )}
    </>
  )
}

export default function Analysis({ goCheckin }) {
  const { data: a, error, loading } = useLoad(analyze7Days)
  if (loading || error) return <><h1>AI Analysis</h1><Status loading={loading} error={error} /></>
  const empty = !a.stats && !a.habit

  return (
    <>
      <h1>AI Analysis</h1>
      <p className="muted">
        {empty ? 'Last 7 days' : `Based on ${a.days} check-in day${a.days === 1 ? '' : 's'} out of the last 7`}
        {' '}· calculated on your device with simple rules (no AI model yet)
      </p>

      {empty && (
        <div className="card center">
          <p>No data yet. Complete a check-in or tick a habit to see your analysis.</p>
          <button className="primary" onClick={goCheckin}>Complete Check-in</button>
        </div>
      )}

      {a.stats && (
        <div className="grid">
          <div className="card"><div className="icon">🌙</div><div className="muted">Average Sleep</div><div className="big">{a.stats.sleep} <small>hr</small></div></div>
          <div className="card"><div className="icon">💧</div><div className="muted">Average Water</div><div className="big">{a.stats.water} <small>glasses</small></div></div>
          <div className="card"><div className="icon">🏃</div><div className="muted">Average Exercise</div><div className="big">{a.stats.exercise} <small>min</small></div><div className="muted">Active on {a.stats.exerciseDays} of {a.days} days</div></div>
          <div className="card"><div className="icon">😊</div><div className="muted">Mood Summary</div><Mix m={a.stats.mood} /></div>
          <div className="card"><div className="icon">🥗</div><div className="muted">Food Quality Summary</div><Mix m={a.stats.food} /></div>
        </div>
      )}

      {a.habit && (
        <div className="card">
          <h3>Habit Completion: {a.habit.percent}%</h3>
          <div className="bar"><span style={{ width: `${a.habit.percent}%` }} /></div>
          {a.habit.per.map((p) => (
            <div className="row" key={p.name}><span>{p.name}</span><b>{p.done} / {p.days} days</b></div>
          ))}
          <p className="muted small">Counted from your first tracked day in the last 7 days.</p>
        </div>
      )}

      <AiPanel />
    </>
  )
}
